nameservers:
  - 8.8.8.8
  - 8.8.4.4
blocklist:
  - https://raw.githubusercontent.com/GoWebProd/openvpn-adBlock/master/list/black.list
blockAddress4: 0.0.0.0
blockAddress6: 0:0:0:0:0:0:0:0
configUpdate: true
updateInterval: 1m